### ISSUE TITLE
Requesting Permissions

### ISSUE THREAD

**Issue by BlueStryker** [McFistyBuns/CBTHeat#2]
Hello! I was wondering if you would allow me to incorporate your three CBT mods into the mod I am creating. With your permission I would simply combine your mods into my own, and keep them updated as you make updates. And of course, credit for those mods will go to you. If I don't have your permission, then I'll just create links to your mods as "highly suggested". Thank you for your time and consideration!

**Comment by McFistyBuns** [comment]
Sorry, it seems like Github isn't sending me any notifications, so I'm only just getting this.  Please feel free to use any of my mods.  You're free to modify them to fit your needs and if you think it would be something someone else would find useful feel free to open a pull request and I'll take a look at incorporating it.

**Comment by BlueStryker** [comment]
No worries, and thank you for letting me use your mods. If you'd like to see what I've been working on, take a look at the True Tabletop Conversion (TTC) on the Nexus. Thanks again!

**Comment by CptMoore** [comment]
Hey Bluestryker, since your goal is to reach CBT rules parity, you might want to look into [MechEngineer](https://github.com/CptMoore/MechEngineer), there the MechLab has been changed alot to include many features found in CBT.

**Comment by BlueStryker** [comment]
Thank you for reaching out to me! That mod is exactly the kind of thing I can make use of. I will contact you directly on your mod's page when I have more time to discuss some things about it.
